name: meetsession-staging

services:
  frontend-staging:
    image: ghcr.io/devonsre/meetsession/frontend:staging-latest
    container_name: meetsession-frontend-staging
    ports:
      - "3012:3000"
    restart: unless-stopped
    env_file:
      - .env
