import type { Metadata } from "next";
import "./globals.css";
import { fontsConfig } from "@/fonts"

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${fontsConfig} font-quicksand antialiased min-h-fit h-dvh w-full`}
      >
        {children}
      </body>
    </html>
  );
}
