name: Deployment Pipeline

on:
  push:
    branches:
      - "preprod" # Preproduction
      - "staging" # Staging

  pull_request:
    types:
      - closed
    branches:
      - "main"

jobs:
  staging-deploy:
    name: Deploy changes to staging server
    if: ${{ github.ref == 'refs/heads/staging' }}
    uses: ./.github/workflows/_deploy-job.yml
    with:
      app_name: aforlink
      image_env: staging
      stack_env: frontend
      latest_tag: staging-latest
      compose_file: compose.staging.yaml
      app_dir: "/opt/products/meetsession/staging/frontend"
      ssh_host_secret: AWS_STAGING2_HOST
      ssh_user_secret: AWS_STAGING2_USER
      ssh_pass_secret: AWS_STAGING2_PASS
    secrets: inherit

  production-deploy:
    name: Deploy changes to production server
    if: ${{ github.event.pull_request.merged == true }}
    uses: ./.github/workflows/_deploy-job.yml
    with:
      app_name: aforlink
      image_env: production
      stack_env: frontend
      latest_tag: latest
      compose_file: compose.prod.yaml
      app_dir: "/opt/products/meetsession/frontend"
      ssh_host_secret: MS_PROD_HOST
      ssh_user_secret: MS_PROD_USER
      ssh_pass_secret: MS_PROD_PASS
    secrets: inherit
